### 
POST  http://localhost:3000/post
Content-Type: application/json
# authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY3NTAxODYsImV4cCI6MTYwNjc1MDE5Nn0.XGQ0O2vj-iDEshnM62nVXcOtsLTNotlgLoAl6tb3pVI"

{
  "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY3NTA1NzMsImV4cCI6MTYwNjc1MTU3M30.YH8rkLEgNTOM7U7pDAu37vV4MnASOQU6JaB202rMcY0"
}

###
get http://localhost:3000/login 
Content-Type: application/json

{
  "username": "catlike"
}
