### 
POST  http://localhost:3000/post
Content-Type: application/json
# authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY3NTAxODYsImV4cCI6MTYwNjc1MDE5Nn0.XGQ0O2vj-iDEshnM62nVXcOtsLTNotlgLoAl6tb3pVI"

{
  "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDcwNzMxNTMsImV4cCI6MTYwNzA3NDE1M30.xJGyT6XAaTJzFR_mgA17nks0tIFCpHF9QteT15Ng01M"
}

###
get http://localhost:3000/login 
Content-Type: application/json

{
  "username": "catlike"
}
